region   = "en-GB"

position = "Top"


[modules]
left = [ [ "appLauncher",  "Updates", "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "Tray", "KeyboardLayout", [  "SystemInfo", "Privacy", "MediaPlayer", "Tempo", "Settings" ] ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "vicinae toggle"

[workspaces]
enable_workspace_filling = false

[window_title]
truncate_title_after_length = 100

[settings]
logout_cmd = "loginctl kill-session ${XDG_SESSION_ID}"

[tempo]
clock_format = "%a %d %b %R"

[osd]
enabled = true   # Disabled by default; set to true to enable the OSD overlay
timeout = 1500   # Auto-hide delay in milliseconds
show_volume_percentage = true    # Show percentage text next to volume/mic bar
show_brightness_percentage = true # Show percentage text next to brightness bar

[media_player]
indicator_format = "Icon"

[appearance]
#style = "Solid"
success_color = "#a6e3a1"
text_color = "#cdd6f4"

workspace_colors = [ "#fab387", "#b4befe", "#cba6f7" ]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#1e1e2e"
weak = "#313244"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"
